### ISSUE TITLE
New upstream release soon?

### ISSUE THREAD

**Issue by ghisvail** [Washington-University/CiftiLib#10]
Hi Tim,

Are you planning to tag a new release some time soon? The current `v1.3` is almost a year old and the packaging would benefit from the improvement you made earlier this year.

Thanks,
Ghis

**Comment by coalsont** [comment]
Sure.  I was waiting to see if you found anything else to fix while testing the packaging of it.

**Comment by coalsont** [comment]
Sorry, I forgot to change the version number in CMakeLists.txt, so I deleted and remade the tag on a new commit.

**Comment by ghisvail** [comment]
Cool, thanks. In the future though, please avoid re-tagging releases, as it could lead to problems with version tracking. In case this happens again, please consider just bumping the micro version number.
