### ISSUE TITLE
How to create a new CiftiFile based on an existing one

### ISSUE THREAD

**Issue by acamargofb** [Washington-University/CiftiLib#21]
I am working with Cfiti files, and I want to create a new one with only 1 comumn. The Cifti input comes with 1200 columns.
How do I set the number of columns ?

Thanks a lot in advance,

Aldo Camargo
Postdoctoral fellow at the University of Maryland of Baltimore

**Comment by coalsont** [comment]
Dimensions and mappings need to be modified in a CiftiXML object, which then needs to be passed to a CiftiFile object (XML deals with interpreting the indices, so that File only has to deal with data IO).  To make a 1-column dscalar from an existing dtseries (or most other 2D dense) file:
```
CiftiXML newXML = inputFile.getCiftiXML();
newXML.setMap(CiftiXML::ALONG_ROW, CiftiScalarsMap(1));
CiftiFile outFile;
outFile.setCiftiXML(newXML);
```

**Comment by coalsont** [comment]
If you want to prevent it from being able to do anything other than make a dscalar, so it is more predictable:
```
if (inputFile.getCiftiXML().getMappingType(CiftiXML::ALONG_COLUMN) != CiftiMappingType::BRAIN_MODELS)
{
    throw CiftiException("yell at user here"); //or your preferred exception type
}
CiftiXML newXML;
newXML.setNumberOfDimensions(2);
newXML.setMap(CiftiXML::ALONG_COLUMN, inputFile.getCiftiXML().getBrainModelsMap(CiftiXML::ALONG_COLUMN));
newXML.setMap(CiftiXML::ALONG_ROW, CiftiScalarsMap(1));
```

**Comment by acamargofb** [comment]
Thanks a lot, it now works as expected :)

Aldo
