### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by acamargofb** [Washington-University/CiftiLib#22]
I have installing the CiftiLib, but even I have installed Boost, I am getting this error:

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.

Have a nice day,

Aldo

**Comment by coalsont** [comment]
Did you install boost manually or via your distribution's package manager?  If it isn't installed in a standard system include directory, you will need to use BOOST_ROOT to tell cmake where you installed it.

**Comment by acamargofb** [comment]
I install manually using the steps of this site:
https://www.boost.org/doc/libs/1_61_0/more/getting_started/unix-variants.html
How can I set the BOOST_ROOT ? 
Where do I have to do it?

Aldo

**Comment by coalsont** [comment]
On your cmake command, add `-D BOOST_ROOT=/path/to/your/install`, substituting in the path that you actually installed it to.

If you have admin on this machine and it is linux, you can instead do something like `sudo apt-get install libboost-dev libboost-filesystem-dev` (for debian and friends) and then cmake should be able to find it without help.  On recent debian-family systems, a version of CiftiLib is also available in the package manager, you can try `sudo apt-get install libcifti-dev`.

Out of curiosity, what are you planning to do with CiftiLib?

**Comment by acamargofb** [comment]
Hi Tim,

Thanks a lot for your quick and accurate answers. I fixed the problem now.
We are planning to do some analysis on  Cifti images using sample entropy.
So far, I made it to work on my PC, but I am trying to install it on my
colleague.

Thanks a lot and have a nice day,

Aldo
