### ISSUE TITLE
Installation on Red Hat Linux

### ISSUE THREAD

**Issue by acamargofb** [Washington-University/CiftiLib#24]
Hi,

I am trying to install this library on a server which uses Red Hat Linux as Operative System. I don't have access as root user, how can I install the library ?

Thanks a lot and have a nice day,

Aldo Camargo

**Comment by coalsont** [comment]
If you only need to build something against it, you can use the standard install prefix mechanisms of cmake (at either configure or install time) to install it somewhere inside your home directory instead (wherever this page says "UNIX", pretend it says linux):

https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html

You will then need to point whatever you are building at that folder for it to find CiftiLib.

If you need it for a prebuilt binary, the easiest solution is probably to get the CiftiLib .so files from whoever built the binary, and then use the `LD_LIBRARY_PATH` environment variable.
