### ISSUE TITLE
versioning library

### ISSUE THREAD

**Issue by igor-raits** [Washington-University/CiftiLib#3]
please add versioning to shared libraries. matching with version I think is good.

**Comment by coalsont** [comment]
To be honest, I had put off thinking about how to make it work as a shared library - private members are currently declared in the headers, so it isn't set up for ABI stability, it would need some work.

It should be building as static libraries by default.  I'd be interested to hear use cases where having it as a shared library would be a better idea.

**Comment by igor-raits** [comment]
In Fedora we don't allow static libraries to package (only as exception and it's not best practice tbh). So we need to have shared library if we want to package (and I want, because I'm working on https://fedoraproject.org/wiki/SIGs/NeuroFedora)

**Comment by igor-raits** [comment]
I can prepare patches in a few days if you want. About versioning - there are no problems: just change soversion if you changing API/ABI

**Comment by coalsont** [comment]
Patches would be nice, I haven't done shared libraries before.

**Comment by coalsont** [comment]
Another potential issue for packaging: currently, it builds 3 separate libraries, one with the very generic name "Common".  These should probably be merged into one library for ease of use as a binary package.

I'd also like to keep the ability to easily build it as static libraries, for users that already use it that way.  Perhaps have it build both shared and static, but only have shared as an install target?  I think I'll try setting this up in a separate branch, to see if it does what you want.

**Comment by coalsont** [comment]
The shlib-test branch is an initial stab at this and #4 (currently installing all headers to $PREFIX/include/Cifti), let me know if it is on the right track.

**Comment by coalsont** [comment]
There is also a pair of defines that are used in library headers to support the use of either QT or libxml2, which could make use as a system library a little more interesting, as projects that use it must use the same define that the library was compiled with.  For the details, look in AString.h or XmlAdapter.h.  If nothing else, as part of packaging, you could just define the appropriate one at the top of AString.h (which gets included by XmlAdapter.h), but I am open to other solutions.

**Comment by igor-raits** [comment]
```
+#TODO: lib64 handling?
+INSTALL(TARGETS Cifti-shared DESTINATION lib) 
```

Look at https://github.com/stnava/ANTs/commit/2e01d146d4be1aa566301b3cd5af0155f14e3f74

Other looks good, but I've not tested.

**Comment by coalsont** [comment]
I have added ${LIB_SUFFIX} to the simplest place, and also made shared library compilation (and install targets) optional, enabled with cmake -DCIFTI_BUILD_SHARED:BOOL=TRUE .  I did this because building both static and shared libraries compiled each source file twice.  The static build targets might belong in an ELSE of that condition, but would need editing of the subdirectory CMakeLists.txt again.

**Comment by ghisvail** [comment]
> use cases where having it as a shared library would be a better idea.

Packaging. Most Linux distributions recommend, if not require, libraries to be distributed as DSO.

> it isn't set up for ABI stability

No problem. Then, the usual convention is to use `0` as the soversion, meaning we don't currently care about ABI compatibility.

**Comment by coalsont** [comment]
So, like commit 90d2a56d7ec7b4707ecb1524fbbdcf61ffff4743?

**Comment by ghisvail** [comment]
`VERSION` can remain `1.3` since this is what your latest tag suggests, what matters here is the value of `SOVERSION` which should be set to 0 (what you just did).

**Comment by coalsont** [comment]
shlib-test is now merged into master.

**Comment by coalsont** [comment]
> ... the usual convention is to use 0 as the soversion, meaning we don't currently care about ABI compatibility.

How does packaging handle this, that is, if the ABI isn't tracked, and a new package version is made from a new version of the source, does the packaging build system somehow automatically rebuild other packages that depend on it?

**Comment by ghisvail** [comment]
> does the packaging build system somehow automatically rebuild other packages that depend on it?

You are correct. This is called a [transition](https://wiki.debian.org/Teams/ReleaseTeam/Transitions).

**Comment by coalsont** [comment]
> You are correct. This is called a transition.

That process doesn't look particularly automatic (get approval from release team, do new uploads on all dependents), and appears to be needed even when ABI versions are tracked.  I'll investigate adding some ABI stability when there is an ABI-breaking change to consider (might be a while before that happens, though).

**Comment by ghisvail** [comment]
> That process doesn't look particularly automatic [...]

Did you expect it to be? The synchronization and notification is actually automatic, but who would be to blame if an automatic rebuild lead to a broken archive? For ciftilib, probably not a big deal because it is a fairly niche package, but think `glibc`, `libstdcpp`, `libpng`...

> [...] and appears to be needed even when ABI versions are tracked.

It is required whenever your package becomes a runtime dependency for any other package. Until then, transitions are not required actually.

> I'll investigate adding some ABI stability when there is an ABI-breaking change to consider.

The lack of ABI stability is not a deal-breaker since a `soversion` of 0 should signal potential client application that ABI stability is not guaranteed at this point. A lot of packages are available in the archive with a soversion of 0, especially in the science section where ABI stability is often not considered until much later, if ever.

Also since your library is C++ and not C, ABI stability will be more challenging to achieve. I can suggest using semantic versioning with either `VERSION_MAJOR` or `VERSION_MAJOR.VERSION_MINOR` as the `soversion`, depending on when you allow API / ABI breaking changes to happen.

**Comment by coalsont** [comment]
> Did you expect it to be?

Well, an ABI change without an API change is supposed to simply work on recompile of the dependent, right?  Just like an update with no ABI or API change should work without a recompile of the dependent?  If you trust the developer to say an update is ABI-compatible (or is this manually tested by the maintainer even for minor libraries?  obviously something as critical as glibc deserves more rigorous testing), it seems like you could also trust them to say it is API-compatible but the ABI changed.

> The synchronization and notification is actually automatic, but who would be to blame if an automatic rebuild lead to a broken archive?

Perhaps I was assuming more separation between the build system and the distribution repositories than actually exists (detect soversion change, recompile the dependent tree, and not publish any rebuilt packages to repository unless all builds in the tree succeed (using the same source version as last published binary package?  can of worms...)).  Of course, it would also need to bump the binary package version somehow...I don't know if it could be workable in practice, as it isn't something I've dealt with.

> A lot of packages are available in the archive with a soversion of 0 [...]

I see.
