### ISSUE TITLE
Support for Qt5

### ISSUE THREAD

**Issue by ghisvail** [Washington-University/CiftiLib#9]
Does CiftiLib support Qt5? Qt4 support [ended last December](http://blog.qt.io/blog/2015/12/18/introducing-long-term-support/) to the benefit of Qt5 (version 5.6 being supported for 3 years). I suspect Linux distributions will stop providing Qt4 at some point, so supporting Qt5 would future proof the library in that regard.

**Comment by coalsont** [comment]
I'll have to try it and see, but since it uses so little of QT, I wouldn't be surprised if it just worked.

**Comment by coalsont** [comment]
commit ed7492a009e1ba6d24e405f98f627ccf9a4ae73e builds against Qt5 on debian testing, but I haven't tried to use it on any files yet.  Do you know what target_link_libraries does on a library target?  Would it be better to include Qt5's mandated compiler flags a different way?

**Comment by coalsont** [comment]
The new tests pass under Qt5, with identical output files to Qt4, so I think this is fine.
